UPDATE APP.RESTAURANTS R
SET R.REVIEW_COUNTER = (SELECT COUNT(*) FROM REVIEWS RW WHERE RW.ID_RESTAURANT = R.ID), R.GLOBAL_REVIEW = (SELECT SUM(RW.GLOBAL_VALUE) FROM REVIEWS RW WHERE RW.ID_RESTAURANT = R.ID)
