
DROP INDEX user_id;
DROP INDEX user_password_id;
DROP INDEX token_idx;
DROP INDEX restaurant_owner_idx;
DROP INDEX restaurant_name_idx;
DROP INDEX restaurant_places_idx;
DROP INDEX restaurants_cuisines_idx;
DROP INDEX orari_idx;
DROP INDEX photos_idx;
DROP INDEX reviews_idx;



DROP TABLE NOTIFICATIONS_RESTAURANT;
DROP TABLE NOTIFICATIONS_PHOTO;
DROP TRIGGER delete_old_tokens_trigger;
DROP TABLE TOKENS;
DROP TABLE RESTAURANTS_CUISINES;
DROP TABLE CUISINES;
DROP TABLE REVIEWS;
DROP TABLE PHOTOS;
DROP TABLE ORARIO;
DROP TABLE RESTAURANTS;
DROP TABLE USERS;
DROP TABLE cities;
DROP TABLE regions;
DROP TABLE states;


