UPDATE APP.REVIEWS R
SET ID_PHOTO = (SELECT ID FROM PHOTOS P WHERE P.ID_RESTAURANT = R.ID_RESTAURANT FETCH FIRST 1 ROWS ONLY)
WHERE R.ID_CREATOR = (SELECT ID_CREATOR FROM REVIEWS REV WHERE REV.ID_RESTAURANT = R.ID_RESTAURANT ORDER BY DATE_CREATION, ID_CREATOR FETCH FIRST 1 ROWS ONLY)
        AND R.DATE_CREATION = (SELECT REV.DATE_CREATION FROM REVIEWS REV WHERE REV.ID_RESTAURANT = R.ID_RESTAURANT ORDER BY DATE_CREATION, ID_CREATOR FETCH FIRST 1 ROWS ONLY)



